Fix `--require-hashes` error on Heroku (#71)
## Describe your changes
Get rid of hashes due to downstream problem of `xgboost` package.

Error output:
```console
         Downloading virtualenv-20.28.0-py3-none-any.whl (4.3 MB)
       Collecting wrapt==1.17.0 (from -r requirements.txt (line 1120))
         Downloading wrapt-1.17.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (89 kB)
       Collecting xgboost==2.1.3 (from -r requirements.txt (line 1187))
         Downloading xgboost-2.1.3-py3-none-manylinux_2_28_x86_64.whl (153.9 MB)
       Collecting zipp==3.21.0 (from -r requirements.txt (line 1197))
         Downloading zipp-3.21.0-py3-none-any.whl (9.6 kB)
       Collecting nvidia-nccl-cu12 (from xgboost==2.1.3->-r requirements.txt (line 1187))
       ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
           nvidia-nccl-cu12 from https://files.pythonhosted.org/packages/ed/1f/6482380ec8dcec4894e7503490fc536d846b0d59694acad9cf99f27d0e7d/nvidia_nccl_cu12-2.23.4-py3-none-manylinux2014_x86_64.whl (from xgboost==2.1.3->-r requirements.txt (line 1187))
 !     Error: Unable to install dependencies using pip.
 !     
 !     See the log output above for more information.
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

## Non-obvious technical information


## Checklist before requesting a review
- [x] The code runs successfully.

```console
michaelp@Mac ucpd-incident-scraper % make update
uv run python -m incident_scraper update
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/michaelp/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
Beginning the UCPD Incident scraping process.
Finished with the UCPD Incident scraping process.
Waiting up to 5 seconds.
Sent all pending logs.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1733869367.760142 2582745 init.cc:229] grpc_wait_for_shutdown_with_timeout() timed out.
michaelp@Mac ucpd-incident-scraper %
```